### ISSUE TITLE
Scala mismatch in dl4j-spark in sbt project

### ISSUE THREAD

**Issue by vzamboni** [deeplearning4j/deeplearning4j#1655]
I am using dl4j-spark with scala 2.10 and building with sbt on a Windows machine with java 8. When I try with sbt assembly I get the error:
https://gist.github.com/vzamboni/9022a3e135733e04d64560e33d9ac943

My build.sbt is:
https://gist.github.com/vzamboni/b9eb16786e55411876161b88e524bb38

There a scala mismatch between scala 2.10 and 2.11 in dl4j-spark module.
Its pom creates the artifact from a scala.binary.version variable (in my case should be 2.10) but I cannot find a way to set it in my build.sbt.

**Comment by AlexDBlack** [comment]
There was (with previous releases) some issues with spark versions (specifically wrong spark versions being included due to bugs with how maven handles properties - i.e., spark 2.11 in dl4j-spark_2.10). Thas should be fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/1904

Next release (0.5.0) will be out soon (few days at most). That should fix these issues properly. If you still run into issues with that, re-open the issue.

**Comment by sushant-hiray** [comment]
Hi @AlexDBlack ,

I've a similar build.sbt as of @vzamboni . I'm currently using the version 0.5.0, however I still face incompatible version issue when using scala 2.10.6
Following is the relevant error log.

```bash
[error] Modules were resolved with conflicting cross-version suffixes in {file:<REDACTED>
[error]    org.apache.spark:spark-launcher _2.10, _2.11
[error]    org.apache.spark:spark-graphx _2.10, _2.11
[error]    org.json4s:json4s-ast _2.10, _2.11
[error]    org.apache.spark:spark-catalyst _2.10, _2.11
[error]    org.apache.spark:spark-network-shuffle _2.10, _2.11
[error]    com.typesafe.akka:akka-actor _2.10, _2.11
[error]    com.twitter:chill _2.10, _2.11
[error]    org.apache.spark:spark-streaming _2.10, _2.11
[error]    org.apache.spark:spark-sql _2.10, _2.11
[error]    org.json4s:json4s-jackson _2.10, _2.11
[error]    com.fasterxml.jackson.module:jackson-module-scala _2.10, _2.11
[error]    org.scalanlp:breeze-macros _2.10, _2.11
[error]    org.json4s:json4s-core _2.10, _2.11
[error]    org.apache.spark:spark-unsafe _2.10, _2.11
[error]    org.spire-math:spire _2.10, _2.11
[error]    org.scalanlp:breeze _2.10, _2.11
[error]    com.typesafe.akka:akka-remote _2.10, _2.11
[error]    com.typesafe.akka:akka-slf4j _2.10, _2.11
[error]    org.spire-math:spire-macros _2.10, _2.11
[error]    org.apache.spark:spark-core _2.10, _2.11
[error]    org.apache.spark:spark-network-common _2.10, _2.11
[error]    org.apache.spark:spark-mllib _2.10, _2.11
java.lang.RuntimeException: Conflicting cross-version suffixes in: org.apache.spark:spark-launcher, org.apache.spark:spark-graphx, org.json4s:json4s-ast, org.apache.spark:spark-catalyst, org.apache.spark:spark-network-shuffle, com.typesafe.akka:akka-actor, com.twitter:chill, org.apache.spark:spark-streaming, org.apache.spark:spark-sql, org.json4s:json4s-jackson, com.fasterxml.jackson.module:jackson-module-scala, org.scalanlp:breeze-macros, org.json4s:json4s-core, org.apache.spark:spark-unsafe, org.spire-math:spire, org.scalanlp:breeze, com.typesafe.akka:akka-remote, com.typesafe.akka:akka-slf4j, org.spire-math:spire-macros, org.apache.spark:spark-core, org.apache.spark:spark-network-common, org.apache.spark:spark-mlliv
```

**Comment by LooooongTran** [comment]
Seeing scala version issues. OS X / MAC / Scala
This is my build.sbt file:
https://gist.github.com/LooooongTran/d69fbe455ab9c8399a898dfe09225cfd

And this is the error log I get when I run "sbt clean; sbt compile"
https://gist.github.com/LooooongTran/d5a2bca96fabfc812ad2b2781063d236

This error goes away when I change my build.sbt file to use scala version 2.11.x  instead of 2.10.x.

I've tried scala versions 2.10.6/5/4/3/2/1  all with the same result.

**Comment by AlexDBlack** [comment]
@LooooongTran Can you run the equivalent of "mvn dependency:tree" with SBT? (I'm not that familiar with it, but looks like there's a few options there to print out the whole dependency tree).
That'll hopefully tell us where this is being pulled in from.

**Comment by LooooongTran** [comment]
@AlexDBlack please see attached files for the dependency trees.  I generated one for scala 2.10 and one for 2.11.  They're big files, hope they can help.  The only dependency in the project at the time was

libraryDependencies ++= Seq(
    "org.deeplearning4j" %% "dl4j-spark" % VERSIONS("dl4j")
)


[scala2.10dependencytree.txt](https://github.com/deeplearning4j/deeplearning4j/files/495834/scala2.10dependencytree.txt)
[scala2.11dependencytree.txt](https://github.com/deeplearning4j/deeplearning4j/files/495835/scala2.11dependencytree.txt)

**Comment by agibsonccc** [comment]
This has been fixed.
