### ISSUE TITLE
Wrong results from wordsNearest after vector math

### ISSUE THREAD

**Issue by uccollab** [deeplearning4j/deeplearning4j#3310]
**Issues description**
With the pretrained google vectors with 300 dimensions, I obtain results differents from the officials. To be more specific what I'm trying to do is the subtraction between two vectors, using the wordsNearest(positive,negative,top) method. As suggested by @raver119 on the channel I use setModelUtils(new FlatModelUtils()) before calling wordsNearest, in order to avoid normalization. Still I'm getting strange results. For example in the DL4J W2V page there are soem examples that I'm not able to reproduce (for example: Library-Books = Hall. I can't obtain this)

**here the code:**
 https://gist.github.com/uccollab/2465bc204bb6d8c5feadc7a96235b841

**Comment by raver119** [comment]
and where's the results?

**Comment by raver119** [comment]
I've fixed one of possible issues here: FlatModelUtils was missing unitVec call on both vectors before cosineSim

**Comment by uccollab** [comment]
Deleted an re-download maven. The issue is still here, here's some example:
Iraq - Violence = Expected Jordan, obtained:
**[Iraqi, Iraqis, Kuwait, oust_Saddam_Hussein, Saddam_Hussein, topple_Saddam_Hussein, Iraqi_exiles, iraq, Saddam, Chalabi]**
President - Power = Expected Prime Minister, obtained:
**[president, Vice_President, Presdient, President_Elect, Preisdent, PRESIDENT, Pesident, Chairman, CEO, Presi_dent]**
Library - Books = Expected Hall, obtained:
**[Public_Library, library, Historical_Museum, Municipal_Building, Courthouse, Branch_Library, Museum, Historic_Courthouse, Annex_Building, Civic_Center]**

**Comment by raver119** [comment]
Aha.
Do vector math manually then.
Get two vectors, "library" and "books", do subtraction, and and apply call to BaseModelUtils.wordsNearest(INDArray, int)

**Comment by uccollab** [comment]
Tried (here's the code fragment: https://gist.github.com/uccollab/4b2822c0a9a88336ff703dd52491c896)
Here's the result (a bit different, still nothing similar to the paper's results):
Iraq - Violence = _Expected_ Jordan, _obtained:_
**[Iraq, Afghanistan, Iraqi, Iraqis, inIraq, Baghdad, topple_Saddam_Hussein, oust_Saddam_Hussein, iraq, Afghan_istan, Saddam_Hussein]**
President - Power = _Expected_ Prime Minister, _obtained:_
**[President, president, Vice_President, Presdient, Presi_dent, Preisdent, Pesident, Presdent, Chairman, Pres, CEO]**
Library - Books = _Expected_ Hall, _obtained:_
**[Library, Public_Library, library, Branch_Library, Libary, Libraries, LIbrary, Public_Libraries, Historical_Museum, Library_Bookmobile_#:##-#, Public_Libary]**

Any chance that I should remove the setModelUtils(new FlatModelUtils()) now that I'm trying it manually?

**Comment by raver119** [comment]
`parola.sub(parola1);`

That's mistake. It should be `parola.subi(parola1);`

**Comment by raver119** [comment]
And please, use  BasicModelUtils. Just make 1 run with library and books. Please note the case.

**Comment by uccollab** [comment]
Did it, the results are still similar:
Library - Books = __Expected__ Hall, __obtained__:
**[Library, Public_Library, library, Historical_Museum, Municipal_Building, Courthouse, Branch_Library, Museum, Historic_Courthouse, Annex_Building]**
The updated code is here: https://gist.github.com/uccollab/c6a5c2059265fde71fe95496f7a09788

**Comment by raver119** [comment]
Please note the case. Low case. `library` and `books`

**Comment by uccollab** [comment]
Tried with lowercase: please note that the information on the DL4J website are quite ambiguous since words like "Library" and "Books" in the examples are written with the forst letter capitalized. Here's the results (code is the same):

library - books = _Expected_ Hall (or hall?), _obtained_:
**[library, Library, Terraceview_Lodge, rec_center, Macomb_OU_INCubator, skate_park, Municipal_Building, riverfront_walkway, Maude_Cobb, skatepark]**

**Comment by raver119** [comment]
Okay, let me download google news model, and check it. Now your code looks valid.

**Comment by raver119** [comment]
As discussed in gitter, same results are obtained via python libraries. So issue isn't math, but vectors being changed over time, since first introduction of w2v.
