### ISSUE TITLE
mixup implementation runs out of memory on GPU

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/deeplearning4j#4283]
#### Issue Description

Please describe our issue, along with:
I have implemented mixup in DL4J as a preprocessor. See https://gist.github.com/fac2003/a2dd08041f34ad1abd71c2c12e7d1d1c for the implementation.
This implementation should work with any problem where a multidataset is used.

Running this on a dataset with ~3M examples per epoch fails after the first epoch with out of memory error on the GPU (see error below). This looks like a garbage collection error/memory leak on the GPU, but I am not sure how I should address it. Any suggestions?  

21:46:37.195 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 0
0       0.243430        0.500000        0.993482        0.998034        0.995753        174758  0.053511        0.969991        1       0.984767        23526   1.593343      173619  1139
Exception in thread "main" java.lang.RuntimeException: Failed to allocate 18472960 bytes from DEVICE [1] memory
        at org.nd4j.jita.memory.CudaMemoryManager.allocate(CudaMemoryManager.java:58)
        at org.nd4j.jita.workspace.CudaWorkspace.alloc(CudaWorkspace.java:197)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:451)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:261)
        at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:64)
        at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:326)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1468)
        at org.nd4j.linalg.jcublas.JCublasNDArray.leverageTo(JCublasNDArray.java:592)
        at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1426)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1296)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:174)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1153)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:965)
        at org.campagnelab.dl.framework.training.SequentialTrainer.train(SequentialTrainer.java:39)
        at org.campagnelab.dl.framework.tools.TrainModel.train(TrainModel.java:377)
        at org.campagnelab.dl.framework.tools.TrainModel.execute(TrainModel.java:198)
        at org.campagnelab.dl.framework.tools.TrainModel.execute(TrainModel.java:92)
        at org.campagnelab.dl.genotype.learning.TrainModelG.main(TrainModelG.java:30)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.1
Cuda compilation tools, release 8.0, V8.0.61
cudnn@6.0
 NVIDIA-SMI 384.90                 Driver Version: 384.9

21:46:13.948 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
21:46:22.976 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
21:46:26.259 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
21:46:26.259 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [72]; Memory: [8.9GB];
21:46:26.259 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
21:46:26.261 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11715084288]
21:46:26.261 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11715084288]
21:46:26.261 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11715084288]
21:46:26.261 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11715084288]

#### Contributing

This seems like a good way to troubleshoot the GPU garbage collection mechanism.

**Comment by raver119** [comment]
I don't see, what WorkspaceMode is used. Mind showing?

**Comment by raver119** [comment]
Plus, why you're using INDArray.detach()? What's the idea?

**Comment by fac2003** [comment]
Workspace:
21:46:30.853 [main] INFO  o.d.nn.graph.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: NONE; inference: SEPARATE]
The detach was an attempt to release memory, but it still the same out of memory, with or without it.

**Comment by fac2003** [comment]
I create INDArrays in detached mode initially to give the async that wraps the iterator the ability to allocate to the GPU of its choice.

**Comment by raver119** [comment]
> WorkspaceModes set to [training: NONE; inference: SEPARATE]

I see that's the problem. Set training workspace to the same: SEPARATE. That's what causes problem.
Should be fixed long ago on master, though.

> I create INDArrays in detached mode initially to give the async that wraps the iterator the ability to allocate to the GPU of its choice.

No-no. That's wrong approach. Async iterator handles that. Every single allocation within async iterator happens on corresponding device when it works with ParallelWrapper. And detach() does the same, but without workspace, so your NDArrays do not benefit from preallocated pools of memory, despite they are still used.

**Comment by fac2003** [comment]
OK, thank for the pointer, I will try to switch to SEPARATE. 
I still don't understand anything about workspaces (I could not find any useful high-level doc..)

**Comment by raver119** [comment]
https://deeplearning4j.org/workspaces

**Comment by fac2003** [comment]
Thank you, yes I have read this, still not useful when you don't know what workspaces are to start with.  The doc should explain the design ideas, why workspaces are needed, and what the different modes do. Specifically, what is the workspace loop? How is a loop initiated and terminated? Without this definition, the text in the workspaces doc you pointed me to is not useful.

**Comment by raver119** [comment]
Ah, you mean ND4J level doc. Ye, that part is missing... Not too many people wonder about that.
Had you checked comments in examples? https://github.com/deeplearning4j/dl4j-examples/blob/master/nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx15_Workspaces.java

**Comment by fac2003** [comment]
Thanks, I was not aware of this doc. I will read.
