### ISSUE TITLE
Word2Vec.wordsNearest appears broken - returns repeats of the nearest word

### ISSUE THREAD

**Issue by dkincaid** [deeplearning4j/deeplearning4j#601]
The wordsNearest method on Word2Vec model seems to be only returning the nearest word and repeating it n times:

```clojure
(.wordsNearest model "snap" 5)
["HASHNUM-55" "HASHNUM-55" "HASHNUM-55" "HASHNUM-55" "HASHNUM-55"]

(.wordsNearest model "rabies" 5)
["embryo" "embryo" "embryo" "embryo" "embryo"]
```

**Comment by agibsonccc** [comment]
This should be fixed with the merge tonight. Re open if neccessary.

**Comment by dkincaid** [comment]
Still seeing the same behavior after `git pull` and `mvn install`. Interestingly, the results are a bit different though. It's returning different words for the same model:

```clojure
(.wordsNearest model "snap" 5)
["sid*" "sid*" "sid*" "sid*" "sid*"]

(.wordsNearest model "rabies" 5)
["snyder," "snyder," "snyder," "snyder," "snyder,"]
```
