### ISSUE TITLE
C-LSTM with mask

### ISSUE THREAD

**Issue by liweigu** [deeplearning4j/deeplearning4j#6316]
I'm training a model to use time-serial images to predict new images, using convolutional LSTM, set RnnToCnnPreProcessor to the first layer(ConvolutionLayer). In order to use n images to predict new n images, i'm using the 'many-to-many', set feature and label both are of (n x 2) size, and set featuresMask as [1,1..,1,0,...,0], set labelsMask as [0,0,...,0,1,...,1]. But it got error :
'Expected rank 4 mask array for 2D CNN layers. Mask arrays for 2D CNN layers must have shape [batchSize,channels,X,Y]'.
It seems the featuresMask is applied to input as CNN, how to apply it to input as RNN?

As my raw code is a bit confused, i re-organized the code at
https://gist.github.com/liweigu/f0dafd8045d766b39c23e1b52938b2ac
(Assuming minibatch = 1, the code is simplied. I can add more code if needed.)

**Comment by AlexDBlack** [comment]
Thanks for the code, I was able to reproduce the issue quickly.

Looks like this is a bug - a release or two back we switched the CNN masking from 2d to broadcastable 4d, to avoid ambiguity and allow greater flexibility with the type of masking for CNNs.
However, this wasn't updated in the CNN to/from RNN preprocesors (looks like they just got forgotten).
I'm working on a fix now.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6319
Just waiting on full test run before merging.

**Comment by liweigu** [comment]
Thank you!
I'll re-test it then.

**Comment by liweigu** [comment]
I'm still getting error, please check it at:
https://gist.github.com/liweigu/8af223c3e245775d11f276cfe26e28ef

**Comment by AlexDBlack** [comment]
@liweigu Did you upgrade to snapshots first, and build with mvn -U option to ensure you got the latest snapshots?
If you're still on 1.0.0-beta2, then of course you won't have the fix...

**Comment by liweigu** [comment]
I'm using snapshots and I've upgraded it with mvn -U option.

**Comment by AlexDBlack** [comment]
OK, I'll re-run your code later and see.
I did add a unit test derived from your code though, when implementing the fix.

**Comment by liweigu** [comment]
Here's the full code for getComputationGraph():
https://gist.github.com/liweigu/2e240e3532a8478080f291d9e370efa7

**Comment by AlexDBlack** [comment]
I'm not able to reproduce this. Here's the exact code I ran, derived from your code: https://gist.github.com/AlexDBlack/916dc4dd2a3df5d5b3241a0f60ff2285

I'm going to close this - it's probably still outdated snapshots on your end. Or, perhaps invalid input.

If you can provide me with something *complete* I can run without any modification or addition to reproduce this - then I'm happy to look into this more.

**Comment by liweigu** [comment]
The jars in the snapshot are just updated to 20180828:
https://oss.sonatype.org/content/repositories/snapshots/org/deeplearning4j/deeplearning4j-nn/1.0.0-SNAPSHOT/
I think that's why i cann't get the fresh jars.
Maybe something wrong in daily build.

**Comment by AlexDBlack** [comment]
That probably explains it then... cc @sshepel

**Comment by sshepel** [comment]
@liweigu sorry for inconvenience, working on that, hope fresh snapshots will be uploaded today.

**Comment by liweigu** [comment]
Thanks ~

**Comment by sshepel** [comment]
@liweigu we got successful build for master, could you please check snapshots repo for new artifacts.

**Comment by liweigu** [comment]
It was fine thereafter.
Just see your message, so i reply this now.
Thanks again.
