### ISSUE TITLE
Problem on Computation Graph with Repeat Vector and ElementWiseVertex 

### ISSUE THREAD

**Issue by Geokats** [deeplearning4j/deeplearning4j#7027]
#### Issue Description

I am trying to implement a bit complicated computationGraph where the output of a LSTM is given to a DenseLayer and the output of the DenseLayer is reshaped to the dimension of the LSTM output so that element-wise product is performed on the two outputs. However I am encountering two exceptions (one when trying to fit on a dataset with masks and another when trying to fit on a dataset without masks).
 
Here is the code for recreating the problem and the two exceptions thrown:

https://gist.github.com/Geokats/167b18603d4be7b5ff8f9007bfdec7b6

#### Version Information

I am using the snapshot version of DL4J with IntelliJ on an Ubuntu 16.04.5 LTS 64-bit system.

#### Contributing

I am very new to DL4J and DL for that matter, but if I could provide any kind of assistance I would gladly do so.

**Comment by AlexDBlack** [comment]
Thanks for reporting. This is a known issue (bug) that has already been fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6945
The fix is currently available on snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

**Comment by Geokats** [comment]
Hello, I am using snapshots and still getting the exception. Also there is a second exception on the element-wise vertex with the product operation.

**Comment by AlexDBlack** [comment]
Ah, thanks. It looks like the issue was not resolved for backprop also, only forward pass in the PR I linked to.

**Comment by AlexDBlack** [comment]
Both issues have been fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/7026
That PR should be merged later today.

**Comment by Geokats** [comment]
Great job! Thank you very much for the quick fix!
