### ISSUE TITLE
UI server not working in a scala SBT project

### ISSUE THREAD

**Issue by jarutis** [deeplearning4j/deeplearning4j#752]
If I try running on sbt assembled file
```
scala -cp target/scala-2.10/cifar.jar org.deeplearning4j.ui.UiServer
```
I get the following error:
```
javax.validation.ValidationException: Unable to find provider: class org.hibernate.validator.HibernateValidator
	at javax.validation.Validation$ProviderSpecificBootstrapImpl.configure(Validation.java:224)
	at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:71)
	at io.dropwizard.Application.run(Application.java:68)
	at org.deeplearning4j.ui.UiServer.createServer(UiServer.java:174)
	at org.deeplearning4j.ui.UiServer.main(UiServer.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```
I use the following dep: `"org.deeplearning4j" % "deeplearning4j-ui" % "0.4-rc3.4-SNAPSHOT"`

**Comment by agibsonccc** [comment]
This has been fixed I believe.

**Comment by sbronzin** [comment]
It's not fixed. I'm getting exactly the same error with an sbt assembled application with deeplearning4j version 5.0.0. Do you have an idea about why this is happening?
