### ISSUE TITLE
Memory leak in inference

### ISSUE THREAD

**Issue by lpaatero** [deeplearning4j/deeplearning4j#8633]
#### Issue Description

Attached model and simple inference program (maven project) seems to demonstrate memory leak.
Program makes inference calls and as byproduct generates AllocationPoint (and some other) objects, until it runs out of memory (in some hours of time).

Maven project & model zip file in [memleak.zip](https://github.com/eclipse/deeplearning4j/files/4099475/memleak.zip)

#### Version Information

* beta6
* CUDA V10.0.130
* NVIDIA driver 418.56
* 5.2.1-2.gbf5c01b-default #1 SMP Mon Jul 15 05:32:47 UTC 2019 (bf5c01b) x86_64 x86_64

**Comment by raver119** [comment]
please upgrade to beta6 or add System.gc() call somewhere in your training loop too fix this. Just not enough pressure to trigger gc. Fixed in beta6.

With best regards,
raver119
22 янв. 2020 г., 22:20 +0300, Lauri Paatero <notifications@github.com>, писал:

**Comment by lpaatero** [comment]
Sorry, I put wrong version into report; Corrected the version to beta6, as it is in pom.xml.
System.gc() does NOT resolve the problem.
There is no training at all, but just inference.

**Comment by raver119** [comment]
Native/GPU memory use seems to be absolutely flat. So whatever happens - happens in java.

Thanks for highlighting this problem, I'll take a look, and once it's confirmed fixed - it'll be in snapshots. However, we've already got rid of AllocationPoint references in current dev master, so it might be already resolved.

**Comment by raver119** [comment]
Updated snapshots should be out tomorrow. Can you please try to run your app with snapshots, and confirm issue is gone?

**Comment by lpaatero** [comment]
Testing full application with current snapshot:
Java -side memory leak is gone.
Unfortunately there is even faster native side leak. I will try to create testcase for it.
Another observation is that toFoatMatrix is now a quite a bit slower.

**Comment by lpaatero** [comment]
The original example seems to create native side memory leak with current snapshot, when evaluation loop is changed to 

```
        for (;;) {
          INDArray in[] = new INDArray[]{ Nd4j.create(data,'c').reshape(new long[]{1, 75, 9, 9}) };
          INDArray[] out = g.output(false, in);          
          
          float fout[][][] = new float[out.length][][];
          for (int ct=0; ct<fout.length; ct++) {
            INDArray w = out[ct].dup('c');
            long[] shape = w.shape();
            w = w.reshape(shape[0],w.length()/shape[0]);
            fout[ct] = w.toFloatMatrix();
          }          
        }
```

**Comment by raver119** [comment]
Thank you very much! Let me check it out.

**Comment by raver119** [comment]
Confirmed. Fix coming.

**Comment by raver119** [comment]
Thanks for highlighting this problem. Things were fixed, and will be available in snapshots later today/early tomorrow.
